# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\")\n\x13StatusUpdateRequest\x12\x12\n\nboot_count\x18\x01 \x01(\x05\"\'\n\x14StatusUpdateResponse\x12\x0f\n\x07message\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUSUPDATEREQUEST']._serialized_start=13
  _globals['_STATUSUPDATEREQUEST']._serialized_end=54
  _globals['_STATUSUPDATERESPONSE']._serialized_start=56
  _globals['_STATUSUPDATERESPONSE']._serialized_end=95
# @@protoc_insertion_point(module_scope)
